#DEPLOYER UN LOG ANALYTICS WORKSPACE 

#ENVOYEZ LES LOGS ET METRICS DE VOTRE KEYVAULT (DIAGNOSTIC SETTING) SUR LE LOG ANALYTICS "GLGL"
#CE LOG ANALYTICS EXISTE DEJA, VOUS DEVREZ UTILISER UN DATASOURCE